import { Router, type IRouter } from "express";
import { db, documentsTable, changelogTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import { randomUUID } from "crypto";
import { anthropic } from "@workspace/integrations-anthropic-ai";
import {
  GenerateDocumentBody,
  RegenerateDocumentParams,
  PromoteDocumentParams,
} from "@workspace/api-zod";
import { getComplianceConstants } from "../../lib/dataManager";

const MAX_REGEN_ATTEMPTS = 2;

const router: IRouter = Router();

router.post("/generation/generate", async (req, res): Promise<void> => {
  const parsed = GenerateDocumentBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.message });
    return;
  }

  const { document_type, target_personas, pipeline_stage_relevance, requirements, document_name } = parsed.data;

  const compliance = getComplianceConstants();
  const complianceText = compliance.constants
    .map((c: any) => `${c.label}: ${c.value}${c.note ? ` (${c.note})` : ""}`)
    .join("\n");

  const briefId = `brief_${randomUUID().slice(0, 8)}`;
  const docId = `gen_${randomUUID().slice(0, 8)}`;

  try {
    const genMessage = await anthropic.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 8192,
      messages: [
        {
          role: "user",
          content: `Generate investor-facing content for Unlock, a UK portfolio intelligence platform.

DOCUMENT TYPE: ${document_type}
DOCUMENT NAME: ${document_name}
TARGET PERSONAS: ${target_personas.join(", ")}
PIPELINE STAGE RELEVANCE: ${pipeline_stage_relevance.join(", ")}

REQUIREMENTS:
${requirements}

COMPLIANCE CONSTANTS (must be accurately reflected):
${complianceText}

RULES:
- Use Unlock terminology: "Founding investor" (not shareholder), "Instant Investment" (not ASA), "EIS/SEIS relief"
- Product tagline: "Clarity, without complexity"
- Never publish discount tier percentages
- Never mention specific commission or fee structures
- All figures must match compliance constants exactly
- Use British English spelling throughout
- Write for sophisticated investors — no marketing fluff

Generate the document content. Return ONLY valid JSON:
{
  "content": "<the full document content in markdown>",
  "metadata": {
    "word_count": <number>,
    "compliance_references_used": ["<which constants were referenced>"],
    "tone_assessment": "<brief assessment of tone>"
  }
}

Return ONLY the JSON.`,
        },
      ],
    });

    const genBlock = genMessage.content[0];
    const genText = genBlock.type === "text" ? genBlock.text : "";

    let generated;
    try {
      const cleaned = genText.replace(/```json\s*/g, "").replace(/```\s*/g, "").trim();
      generated = JSON.parse(cleaned);
    } catch {
      generated = { content: genText, metadata: { word_count: genText.split(/\s+/).length, compliance_references_used: [], tone_assessment: "Unable to assess" } };
    }

    const qcReport = await runQC(generated.content, complianceText, document_type, 1);

    const fileCode = `GEN_${document_type.toUpperCase().replace(/\s+/g, "_").slice(0, 15)}_${docId.slice(4)}`;

    await db.insert(documentsTable).values({
      id: docId,
      file_code: fileCode,
      type: document_type,
      name: document_name,
      filename: `${fileCode}_V1_DRAFT.md`,
      tier: 3,
      category: "Generated",
      lifecycle_status: "DRAFT",
      review_state: qcReport.overall === "pass" ? "CLEAN" : "REQUIRES_REVIEW",
      version: 1,
      last_reviewed: new Date().toISOString().split("T")[0],
      description: requirements.slice(0, 200),
      pipeline_stage_relevance: pipeline_stage_relevance,
      persona_relevance: target_personas,
      upstream_dependencies: [],
      downstream_dependents: [],
      is_generated: true,
      generation_brief_id: briefId,
      generation_attempt: 1,
      qc_report_id: qcReport.overall,
      source_trace: [`Generated by AI on ${new Date().toISOString()}`],
      content: generated.content,
      qc_history: [qcReport],
    });

    await db.insert(changelogTable).values({
      id: randomUUID(),
      action: "DOCUMENT_GENERATED",
      document_id: docId,
      details: `Generated document: ${document_name} (${document_type}). QC result: ${qcReport.overall}. Attempt 1.`,
      triggered_by: "ai_generator",
    });

    const [savedDoc] = await db.select().from(documentsTable).where(eq(documentsTable.id, docId));
    res.json({
      document: {
        id: savedDoc.id,
        file_code: savedDoc.file_code,
        type: savedDoc.type,
        name: savedDoc.name,
        filename: savedDoc.filename,
        tier: savedDoc.tier,
        category: savedDoc.category,
        lifecycle_status: savedDoc.lifecycle_status,
        review_state: savedDoc.review_state,
        version: savedDoc.version,
        last_reviewed: savedDoc.last_reviewed,
        description: savedDoc.description,
        pipeline_stage_relevance: savedDoc.pipeline_stage_relevance,
        persona_relevance: savedDoc.persona_relevance,
        upstream_dependencies: savedDoc.upstream_dependencies,
        downstream_dependents: savedDoc.downstream_dependents,
        is_generated: savedDoc.is_generated,
        generation_brief_id: savedDoc.generation_brief_id,
        generation_attempt: savedDoc.generation_attempt,
        qc_report_id: savedDoc.qc_report_id,
        source_trace: savedDoc.source_trace,
        content: savedDoc.content,
      },
      generated_content: generated.content,
      qc_report: qcReport,
    });
  } catch (err: any) {
    req.log.error({ err }, "Document generation failed");
    res.status(500).json({ error: "Document generation failed. Please try again." });
  }
});

router.post("/generation/:id/regenerate", async (req, res): Promise<void> => {
  const params = RegenerateDocumentParams.safeParse(req.params);
  if (!params.success) {
    res.status(400).json({ error: params.error.message });
    return;
  }

  const [doc] = await db.select().from(documentsTable).where(eq(documentsTable.id, params.data.id));
  if (!doc) {
    res.status(404).json({ error: "Document not found" });
    return;
  }
  if (!doc.is_generated) {
    res.status(400).json({ error: "Only AI-generated documents can be regenerated" });
    return;
  }

  const currentAttempt = doc.generation_attempt || 1;
  if (currentAttempt >= MAX_REGEN_ATTEMPTS) {
    await db
      .update(documentsTable)
      .set({ review_state: "REQUIRES_REVIEW" })
      .where(eq(documentsTable.id, params.data.id));

    await db.insert(changelogTable).values({
      id: randomUUID(),
      action: "MANUAL_REVIEW_REQUIRED",
      document_id: params.data.id,
      details: `Maximum regeneration attempts (${MAX_REGEN_ATTEMPTS}) reached. Manual review required.`,
      triggered_by: "system",
    });

    const [updatedDoc] = await db.select().from(documentsTable).where(eq(documentsTable.id, params.data.id));
    res.json({
      document: updatedDoc,
      generated_content: updatedDoc.content || "",
      qc_report: { overall: "fail", checks: [], fail_count: 0, warnings: ["Maximum regeneration attempts reached"], qc_attempt: currentAttempt },
    });
    return;
  }

  const compliance = getComplianceConstants();
  const complianceText = compliance.constants
    .map((c: any) => `${c.label}: ${c.value}${c.note ? ` (${c.note})` : ""}`)
    .join("\n");

  const previousQcHistory = (doc.qc_history as any[]) || [];
  const lastQc = previousQcHistory[previousQcHistory.length - 1];

  const failedChecks = lastQc?.checks?.filter((c: any) => c.result === "fail") || [];
  const failSummary = failedChecks.map((c: any) => `- ${c.label}: ${c.offending_text || "N/A"} → should be: ${c.correct_version || "N/A"}`).join("\n");

  try {
    const genMessage = await anthropic.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 8192,
      messages: [
        {
          role: "user",
          content: `Regenerate this investor-facing document for Unlock, fixing the QC failures.

DOCUMENT TYPE: ${doc.type}
DOCUMENT NAME: ${doc.name}

PREVIOUS CONTENT:
${doc.content}

QC FAILURES TO FIX:
${failSummary || "No specific failures logged — improve overall quality."}

COMPLIANCE CONSTANTS:
${complianceText}

RULES:
- Fix ALL QC failures listed above
- Use Unlock terminology: "Founding investor", "Instant Investment", "EIS/SEIS relief"
- Product tagline: "Clarity, without complexity"
- Never publish discount tier percentages
- All figures must match compliance constants exactly
- Use British English spelling throughout

Return ONLY valid JSON:
{
  "content": "<the full regenerated document content in markdown>",
  "changes_made": ["<what was fixed>"]
}

Return ONLY the JSON.`,
        },
      ],
    });

    const genBlock = genMessage.content[0];
    const genText = genBlock.type === "text" ? genBlock.text : "";

    let regenerated;
    try {
      const cleaned = genText.replace(/```json\s*/g, "").replace(/```\s*/g, "").trim();
      regenerated = JSON.parse(cleaned);
    } catch {
      regenerated = { content: genText, changes_made: [] };
    }

    const newAttempt = currentAttempt + 1;
    const qcReport = await runQC(regenerated.content, complianceText, doc.type, newAttempt);

    const newQcHistory = [...previousQcHistory, qcReport];

    await db
      .update(documentsTable)
      .set({
        content: regenerated.content,
        generation_attempt: newAttempt,
        qc_history: newQcHistory,
        review_state: qcReport.overall === "pass" ? "CLEAN" : "REQUIRES_REVIEW",
      })
      .where(eq(documentsTable.id, params.data.id));

    await db.insert(changelogTable).values({
      id: randomUUID(),
      action: "DOCUMENT_REGENERATED",
      document_id: params.data.id,
      details: `Regenerated document (attempt ${newAttempt}). QC result: ${qcReport.overall}.`,
      triggered_by: "ai_generator",
    });

    const [updatedDoc2] = await db.select().from(documentsTable).where(eq(documentsTable.id, params.data.id));
    res.json({
      document: updatedDoc2,
      generated_content: regenerated.content,
      qc_report: qcReport,
    });
  } catch (err: any) {
    req.log.error({ err }, "Document regeneration failed");
    res.status(500).json({ error: "Document regeneration failed. Please try again." });
  }
});

router.post("/generation/:id/qc-rerun", async (req, res): Promise<void> => {
  const params = PromoteDocumentParams.safeParse(req.params);
  if (!params.success) {
    res.status(400).json({ error: params.error.message });
    return;
  }

  const [doc] = await db.select().from(documentsTable).where(eq(documentsTable.id, params.data.id));
  if (!doc) {
    res.status(404).json({ error: "Document not found" });
    return;
  }
  if (!doc.content) {
    res.status(400).json({ error: "Document has no content to evaluate" });
    return;
  }

  const compliance = getComplianceConstants();
  const complianceText = compliance.constants
    .map((c: any) => `${c.label}: ${c.value}${c.note ? ` (${c.note})` : ""}`)
    .join("\n");

  const previousQcHistory = (doc.qc_history as any[]) || [];
  const newAttempt = previousQcHistory.length + 1;

  const qcReport = await runQC(doc.content, complianceText, doc.type, newAttempt);

  const newQcHistory = [...previousQcHistory, qcReport];

  const [updated] = await db
    .update(documentsTable)
    .set({
      qc_history: newQcHistory,
      qc_report_id: qcReport.overall,
      review_state: qcReport.overall === "pass" ? "CLEAN" : "REQUIRES_REVIEW",
    })
    .where(eq(documentsTable.id, params.data.id))
    .returning();

  await db.insert(changelogTable).values({
    id: randomUUID(),
    action: "QC_RERUN",
    document_id: params.data.id,
    details: `QC re-run (attempt ${newAttempt}). Result: ${qcReport.overall}. Failures: ${qcReport.fail_count}.`,
    triggered_by: "agent",
  });

  res.json({
    document_id: updated.id,
    review_state: updated.review_state,
    qc_report: qcReport,
  });
});

router.post("/generation/:id/promote", async (req, res): Promise<void> => {
  const params = PromoteDocumentParams.safeParse(req.params);
  if (!params.success) {
    res.status(400).json({ error: params.error.message });
    return;
  }

  const [doc] = await db.select().from(documentsTable).where(eq(documentsTable.id, params.data.id));
  if (!doc) {
    res.status(404).json({ error: "Document not found" });
    return;
  }
  if (doc.lifecycle_status !== "DRAFT") {
    res.status(400).json({ error: "Only DRAFT documents can be promoted" });
    return;
  }
  if (doc.review_state === "REQUIRES_REVIEW") {
    res.status(400).json({ error: "Document requires review before promotion" });
    return;
  }

  const [updated] = await db
    .update(documentsTable)
    .set({
      lifecycle_status: "CURRENT",
      version: (doc.version || 1) + 1,
      last_reviewed: new Date().toISOString().split("T")[0],
    })
    .where(eq(documentsTable.id, params.data.id))
    .returning();

  await db.insert(changelogTable).values({
    id: randomUUID(),
    action: "DOCUMENT_PROMOTED",
    document_id: params.data.id,
    details: `Promoted from DRAFT to CURRENT (v${updated.version})`,
    triggered_by: "agent",
  });

  res.json({
    document_id: updated.id,
    lifecycle_status: updated.lifecycle_status,
    version: updated.version,
    message: `Document promoted to CURRENT (v${updated.version})`,
  });
});

const QC_CHECKLIST_PROMPT = `RUN EXACTLY THESE CHECKS IN THIS ORDER. Do not skip any check.
Do not add checks that are not on this list.

1.  COMPLIANCE_FIGURES — EIS income tax relief stated as 30%
2.  COMPLIANCE_FIGURES — SEIS income tax relief stated as 50%
3.  COMPLIANCE_FIGURES — VCT income tax relief stated as 20%
    (not 30% — VCT was reduced from April 2026)
4.  COMPLIANCE_FIGURES — BPR cap stated as £2,500,000 (not £2.5M)
    with "subject to final enactment" qualifier
5.  COMPLIANCE_FIGURES — Pension IHT change stated as April 2027
    with "subject to final legislation" qualifier
6.  COMPLIANCE_FIGURES — EIS loss relief: if per-pound figure is
    used, it must be ~38.5p (additional rate). If percentage framing
    is used, 38.5% effective reduction is acceptable. Never 20p.
7.  COMPLIANCE_FIGURES — SEIS loss relief: if per-pound figure is
    used, it must be ~27.5p (additional rate). If percentage framing
    is used, up to 72% effective relief is acceptable. Never 22p.
    The figure 22p per pound is PROHIBITED — it is factually wrong.
    Any reference to "22p" as SEIS loss relief is an automatic fail.
8.  TERMINOLOGY — "Instant Investment" used (not ASA/SAFE)
9.  TERMINOLOGY — No prohibited phrases: "game-changing",
    "revolutionary", "disruptive", "guaranteed"
10. TERMINOLOGY — Decumulation Planner status uses approved phrase
    "Specification complete. Prototype build commencing."
    (not "live", "available", "launching soon", "in development")
11. PRODUCT_TAGLINE — "Clarity, without complexity" present
    (only required for Tier 1 documents and investor-facing Tier 3)
12. PORTFOLIO_ARITHMETIC — Any portfolio allocation percentages
    mentioned sum to exactly 100%
13. INVESTMENT_ADVICE — No content constitutes regulated financial
    advice or personal recommendations
14. UNSUBSTANTIATED_CLAIMS — No specific financial projections
    stated as fact without "illustrative" or "varies by" qualifier
15. FCA_STATUS — If Unlock Access is mentioned: "Unlock Access
    does not hold FCA authorisation" stated or clearly implied
16. LOSS_RELIEF_INHERITANCE — If loss relief is mentioned:
    "personal to the original investor" stated or not applicable
17. CAPITAL_AT_RISK — "Capital at risk" appears in any document
    that discusses investment returns
18. ADVISER_CONFIRMATION — Loss relief figures include
    "subject to adviser confirmation"
19. INVESTMENT_MINIMUMS — If a minimum investment figure is
    stated, it must be £40,000 or above. Any figure below
    £40,000 (including £10,000, £10K, "from £10K", "from £5K",
    or any similar low figure) is a compliance failure.
    If no minimum investment figure is stated: return
    result: "pass", note: "No minimum stated — not applicable"
    If the figure is £40,000 or above: return "pass" with
    the figure as evidence.
    If the figure is below £40,000: return "fail" with the
    offending figure and the correct version: "£40,000 minimum".

For each check:
- If the check is not applicable to this document type: return
  result: "pass", note: "Not applicable to document type"
- If the check passes: return result: "pass" with evidence
- If the check fails: return result: "fail" with BOTH
  offending_text (exact quote from document) AND
  correct_version (the corrected text)
- If offending_text and correct_version would be identical:
  return result: "pass", note: "Content already correct"
  DO NOT return a fail if you cannot suggest an actual correction`;

const CHUNK_THRESHOLD = 15000;

function isFalsePositive(check: any): boolean {
  if (check.result !== "fail") return false;

  if (check.offending_text && check.correct_version) {
    const normalise = (s: string) => s.trim().toLowerCase().replace(/\s+/g, " ");
    if (normalise(check.offending_text) === normalise(check.correct_version)) return true;
  }

  if (check.offending_text && !check.correct_version) {
    const noteLower = (check.note || "").toLowerCase();
    if (noteLower.includes("already correct") || noteLower.includes("no correction needed") || noteLower.includes("content is correct")) {
      return true;
    }
  }

  return false;
}

function splitIntoChunks(content: string, maxSize: number): string[] {
  if (content.length <= maxSize) return [content];
  const paragraphs = content.split(/\n\n+/);
  const chunks: string[] = [];
  let current = "";
  for (const para of paragraphs) {
    if (current.length + para.length + 2 > maxSize && current.length > 0) {
      chunks.push(current.trim());
      current = "";
    }
    current += (current ? "\n\n" : "") + para;
  }
  if (current.trim()) chunks.push(current.trim());
  return chunks.length > 0 ? chunks : [content];
}

async function runQCSingle(contentChunk: string, complianceText: string, documentType: string, attempt: number) {
  const message = await anthropic.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 8192,
    messages: [
      {
        role: "user",
        content: `You are a QC evaluator for Unlock, a UK portfolio intelligence platform. Evaluate this document content.

DOCUMENT TYPE: ${documentType}
CONTENT TO EVALUATE:
${contentChunk}

COMPLIANCE CONSTANTS THAT MUST BE ACCURATE:
${complianceText}

${QC_CHECKLIST_PROMPT}

Return ONLY valid JSON:
{
  "overall": "<pass|fail>",
  "checks": [
    {
      "check_number": <1-19>,
      "check_id": "<category from checklist>",
      "label": "<human-readable label>",
      "result": "<pass|fail>",
      "offending_text": "<exact text that fails, or null>",
      "correct_version": "<what it should say, or null>",
      "note": "<explanation or evidence>",
      "source": "<which compliance constant or rule>"
    }
  ],
  "fail_count": <number>,
  "warnings": [],
  "qc_attempt": ${attempt}
}

You MUST return exactly 19 check results, one for each numbered check above, in order.
Return ONLY the JSON.`,
      },
    ],
  });

  const block = message.content[0];
  const text = block.type === "text" ? block.text : "";
  const cleaned = text.replace(/```json\s*/g, "").replace(/```\s*/g, "").trim();
  return JSON.parse(cleaned);
}

function mergeChunkResults(chunkResults: any[], attempt: number) {
  const mergedChecks: any[] = [];
  const checkCount = 19;

  for (let i = 0; i < checkCount; i++) {
    let worstResult = "pass";
    let failingCheck: any = null;

    for (const cr of chunkResults) {
      const check = cr.checks?.find((c: any) => c.check_number === i + 1) || cr.checks?.[i];
      if (check && check.result === "fail") {
        worstResult = "fail";
        failingCheck = check;
      }
    }

    if (failingCheck) {
      mergedChecks.push({ ...failingCheck, check_number: i + 1 });
    } else {
      const firstCheck = chunkResults[0]?.checks?.find((c: any) => c.check_number === i + 1) || chunkResults[0]?.checks?.[i];
      mergedChecks.push(firstCheck ? { ...firstCheck, check_number: i + 1 } : {
        check_number: i + 1,
        check_id: `check_${i + 1}`,
        label: `Check ${i + 1}`,
        result: "pass",
        note: "Not applicable",
        offending_text: null,
        correct_version: null,
        source: null,
      });
    }
  }

  return mergedChecks;
}

async function runQC(content: string, complianceText: string, documentType: string, attempt: number) {
  try {
    const needsChunking = content.length > CHUNK_THRESHOLD;
    const chunks = needsChunking ? splitIntoChunks(content, CHUNK_THRESHOLD) : [content];
    let allChecks: any[];

    let sampledChunks = chunks;
    if (chunks.length > 3) {
      const mid = Math.floor(chunks.length / 2);
      sampledChunks = [chunks[0], chunks[mid], chunks[chunks.length - 1]];
    }
    const actualChunksProcessed = sampledChunks.length;

    if (sampledChunks.length === 1) {
      const result = await runQCSingle(sampledChunks[0], complianceText, documentType, attempt);
      allChecks = result.checks || [];
    } else {
      const settled = await Promise.allSettled(
        sampledChunks.map(chunk => runQCSingle(chunk, complianceText, documentType, attempt))
      );
      const chunkResults = settled
        .filter((r): r is PromiseFulfilledResult<any> => r.status === "fulfilled")
        .map(r => r.value);
      if (chunkResults.length === 0) {
        throw new Error("All chunk QC evaluations failed");
      }
      allChecks = mergeChunkResults(chunkResults, attempt);
    }

    if (allChecks.length < 19) {
      for (let i = allChecks.length; i < 19; i++) {
        allChecks.push({
          check_number: i + 1,
          check_id: `check_${i + 1}`,
          label: `Check ${i + 1}`,
          result: "pass",
          note: "Not returned by evaluator — assumed not applicable",
          offending_text: null,
          correct_version: null,
          source: null,
        });
      }
    }

    let autoResolvedCount = 0;
    for (const check of allChecks) {
      if (isFalsePositive(check)) {
        check.result = "pass";
        check.note = (check.note ? check.note + " | " : "") + "Auto-resolved: offending text matches correction";
        autoResolvedCount++;
      }
    }

    const failCount = allChecks.filter((c: any) => c.result === "fail").length;
    const overall = failCount === 0 ? "pass" : "fail";

    const warnings: string[] = [];
    if (autoResolvedCount > 0) {
      warnings.push(`${autoResolvedCount} false positive(s) auto-resolved`);
    }

    return {
      overall,
      checks: allChecks,
      fail_count: failCount,
      auto_resolved_count: autoResolvedCount,
      warnings,
      qc_attempt: attempt,
      chunking_applied: needsChunking,
      chunks_total: chunks.length,
      chunks_processed: actualChunksProcessed,
      total_checks: allChecks.length,
    };
  } catch (err: any) {
    try {
      const errMsg = err?.message || String(err);
      if (errMsg.includes("JSON") || errMsg.includes("parse")) {
        return {
          overall: "fail",
          checks: [],
          fail_count: 1,
          auto_resolved_count: 0,
          warnings: ["QC response could not be parsed — failing closed for safety"],
          qc_attempt: attempt,
          chunking_applied: content.length > CHUNK_THRESHOLD,
          chunks_processed: 0,
          total_checks: 0,
        };
      }
      throw err;
    } catch {
      return {
        overall: "fail",
        checks: [],
        fail_count: 1,
        auto_resolved_count: 0,
        warnings: ["QC evaluation unavailable — failing closed for safety"],
        qc_attempt: attempt,
        chunking_applied: false,
        chunks_processed: 0,
        total_checks: 0,
      };
    }
  }
}

export default router;
