import { Router, type IRouter } from "express";
import healthRouter from "./health";
import leadsRouter from "./leads";
import documentsRouter from "./documents";
import recommendationRouter from "./recommendation";
import contentRouter from "./content";
import generationRouter from "./generation";
import dashboardRouter from "./dashboard";
import gdocsRouter from "./gdocs";
import callFrameworkRouter from "./call-framework";
import analyticsRouter from "./analytics";
import videosRouter from "./videos";
import acuRouter from "./acu";
import campaignsRouter from "./campaigns";
import templatesRouter from "./templates";
import promptsRouter from "./prompts";
import complianceConstantsRouter from "./compliance-constants";
import importRouter from "./import";
import tasksRouter from "./tasks";
import sheetSyncRouter from "./sheet-sync";
import beliefsRouter from "./beliefs";
import leadBeliefsRouter from "./lead-beliefs";
import leadIntelligenceRouter from "./lead-intelligence";
import workQueueRouter from "./work-queue";
import documentHealthRouter from "./document-health";
import settingsRouter from "./settings";
import contactsRouter from "./contacts";
import campaignsDispatchRouter from "./campaigns-dispatch";
import aircallRouter from "./aircall";
import engineRouter from "./engine";
import eventsRouter from "./events";
import authRouter from "./auth";
import adminRouter from "./admin";

const router: IRouter = Router();

router.use(authRouter);
router.use(adminRouter);
router.use(healthRouter);
router.use(leadsRouter);
router.use(documentsRouter);
router.use(recommendationRouter);
router.use(contentRouter);
router.use(generationRouter);
router.use(dashboardRouter);
router.use(gdocsRouter);
router.use(callFrameworkRouter);
router.use(analyticsRouter);
router.use(videosRouter);
router.use(acuRouter);
router.use(campaignsRouter);
router.use(templatesRouter);
router.use(promptsRouter);
router.use(complianceConstantsRouter);
router.use(importRouter);
router.use(tasksRouter);
router.use("/sheet-sync", sheetSyncRouter);
router.use(beliefsRouter);
router.use(leadBeliefsRouter);
router.use(leadIntelligenceRouter);
router.use(workQueueRouter);
router.use(documentHealthRouter);
router.use(settingsRouter);
router.use(contactsRouter);
router.use(campaignsDispatchRouter);
router.use(aircallRouter);
router.use(engineRouter);
router.use(eventsRouter);

export default router;
