-- Migration 0.9: Populate conversation_question, content_if_unresolved, red_flag_signals, green_flag_signals
-- Safe to run multiple times (UPDATE is idempotent)

UPDATE belief_registry SET conversation_question = 'When your IFA discusses EIS, do they talk about specific companies or just funds?', content_if_unresolved = 'Send Doc 140 — explains why IFA advice stops at fund level and what that means for direct EIS.', red_flag_signals = '["My IFA handles everything including individual EIS deals","I already have a direct EIS advisory relationship"]'::jsonb, green_flag_signals = '["My IFA only mentions EIS funds","I have to find individual deals myself","Nobody helps me evaluate specific EIS companies"]'::jsonb WHERE id = 'U1';

UPDATE belief_registry SET conversation_question = 'How do you think about the correlation between your existing portfolio holdings?', content_if_unresolved = 'Send Doc 190 — Iran effect case study showing hidden correlation across apparently diversified portfolios.', red_flag_signals = '["My portfolio is already well diversified","Correlation risk does not concern me"]'::jsonb, green_flag_signals = '["I had not thought about that","My holdings probably do move together","The 2022 drawdown hit everything at once"]'::jsonb WHERE id = 'U2';

UPDATE belief_registry SET conversation_question = 'What matters most to you when evaluating who provides investment research or tools — independence or brand?', content_if_unresolved = 'Send Doc 120 — Unlock platform overview showing no commission, no AUM fee, no conflicted revenue.', red_flag_signals = '["I prefer established brands regardless of conflicts","Independence does not matter if the product is good"]'::jsonb, green_flag_signals = '["I worry about conflicts of interest","Fee-free sounds too good — how do you make money?","Independence is important to me"]'::jsonb WHERE id = 'U3';

UPDATE belief_registry SET conversation_question = 'When you think about EIS risk, what is the worst-case scenario in your mind?', content_if_unresolved = 'Send Doc 150 — EIS relief mechanics showing max effective loss is 38.5p per pound after all tax reliefs.', red_flag_signals = '["I could lose everything","EIS is too risky for me at any level","I do not want any illiquid exposure"]'::jsonb, green_flag_signals = '["I did not realise the tax relief reduced the downside that much","So the real risk is only 38p in the pound?","That changes how I think about the allocation"]'::jsonb WHERE id = 'U4';

UPDATE belief_registry SET conversation_question = 'What is your experience with early-stage tech investments — do you see the upside potential?', content_if_unresolved = 'Send Doc 160 — early-stage tech return profiles showing asymmetric upside with EIS tax relief floor.', red_flag_signals = '["Early-stage is pure gambling","I only invest in public markets","Tech companies are overvalued"]'::jsonb, green_flag_signals = '["I like the risk/reward profile","Tax relief as a floor is interesting","I have done angel investing before"]'::jsonb WHERE id = 'G1';

UPDATE belief_registry SET conversation_question = 'Have you looked at the total fee load on your current EIS fund investments?', content_if_unresolved = 'Send Doc 140 — comparison of direct EIS vs fund fee structures showing long-term fee drag impact.', red_flag_signals = '["Fund fees are worth it for the diversification","I prefer someone else managing the portfolio"]'::jsonb, green_flag_signals = '["I had not added up all the layers of fees","The fee drag over 3-5 years is significant","I would rather pick direct if I had the tools"]'::jsonb WHERE id = 'G2';

UPDATE belief_registry SET conversation_question = 'If you wanted to invest in individual EIS companies directly, what tools or support would you need?', content_if_unresolved = 'Send Doc 140 — explains the infrastructure gap for direct EIS and how Unlock fills it.', red_flag_signals = '["I can do my own due diligence","I do not need tools, I just need deal flow"]'::jsonb, green_flag_signals = '["I would not know where to start evaluating individual companies","Due diligence on private companies is hard","I need something to help me assess these"]'::jsonb WHERE id = 'G3';

UPDATE belief_registry SET conversation_question = 'Are you aware of the timing advantage of acting before January 2027?', content_if_unresolved = 'BLOCKED — awaiting legal sign-off. Do not send content on this belief.', red_flag_signals = '["I am in no rush","Timing does not affect my decision"]'::jsonb, green_flag_signals = '["I want to be ahead of the crowd","Getting in early matters to me"]'::jsonb WHERE id = 'P1';

UPDATE belief_registry SET conversation_question = 'When you hear EIS is risky, are you thinking about gross loss or loss after tax reliefs?', content_if_unresolved = 'Send Doc 150 — walks through the relief stack showing net risk per pound is 38.5p not 100p.', red_flag_signals = '["Even 38p loss is too much","I do not trust HMRC to honour the reliefs"]'::jsonb, green_flag_signals = '["I assumed I could lose the whole amount","I did not factor in loss relief on top of income tax relief","That reframes the risk significantly"]'::jsonb WHERE id = 'P2';

UPDATE belief_registry SET conversation_question = 'If markets corrected 20-30%, how would that change your view on having uncorrelated holdings?', content_if_unresolved = 'Send Doc 190 — shows how EIS-qualifying companies behave differently in corrections vs correlated public markets.', red_flag_signals = '["I would just buy the dip in public markets","Private companies would be hit harder in a correction"]'::jsonb, green_flag_signals = '["That is exactly when diversification matters","My portfolio has no real hedge","I saw how correlated everything was in 2022"]'::jsonb WHERE id = 'P3';

UPDATE belief_registry SET conversation_question = 'Have you reviewed how the April 2027 pension changes affect your estate plan?', content_if_unresolved = 'Send Doc 170 — analysis of pension IHT changes and impact on estate planning strategies.', red_flag_signals = '["My estate plan is already sorted","Pensions are not part of my estate plan","My adviser is handling this"]'::jsonb, green_flag_signals = '["I had not realised pensions would be in the estate for IHT","That changes everything for my planning","We need to rethink the estate structure"]'::jsonb WHERE id = 'L1';

UPDATE belief_registry SET conversation_question = 'With BPR under pressure, have you considered rolling EIS as an alternative estate planning tool?', content_if_unresolved = 'Send Doc 170 — explains how rolling EIS investments can replace BPR for IHT-efficient wealth transfer.', red_flag_signals = '["BPR still works fine for my situation","I do not want illiquid assets in my estate","EIS and estate planning do not mix"]'::jsonb, green_flag_signals = '["I need a BPR alternative","The two-year qualifying period works for my timeline","Rolling EIS for IHT relief is clever"]'::jsonb WHERE id = 'L2';

UPDATE belief_registry SET conversation_question = 'Do you understand the two-year holding requirement for EIS IHT relief?', content_if_unresolved = 'BLOCKED — awaiting legal sign-off. Do not send content on this belief.', red_flag_signals = '["Two years is too long to lock up capital"]'::jsonb, green_flag_signals = '["Two years is shorter than I expected","That fits my estate planning horizon"]'::jsonb WHERE id = 'L3';

UPDATE belief_registry SET conversation_question = 'Do you see a large enough market for independent EIS due diligence tools?', content_if_unresolved = 'Send Doc 130 — market sizing and competitive landscape for EIS intelligence platforms.', red_flag_signals = '["The market is too niche","EIS is a tiny corner of the market","There will never be enough demand"]'::jsonb, green_flag_signals = '["There are thousands of HNWIs who need this","The IFA gap creates real demand","With the regulatory changes the market is growing"]'::jsonb WHERE id = 'C1';

UPDATE belief_registry SET conversation_question = 'What gives you confidence — or concern — about the team behind a company you invest in?', content_if_unresolved = 'Send Doc 120 — team backgrounds showing domain expertise: Tom King (15yr EIS), Werner (banking tech), Tony Vine-Lott (Barclays).', red_flag_signals = '["The team is too small","I need to see a bigger management team","No track record in this space"]'::jsonb, green_flag_signals = '["The domain expertise is strong","I like that the team has industry background","Tom knows the EIS space well"]'::jsonb WHERE id = 'C2';

UPDATE belief_registry SET conversation_question = 'How important is it to you that the product is already being used by real investors?', content_if_unresolved = 'Send Doc 120 — shows five founding investors actively using the platform, evolved from real DD needs.', red_flag_signals = '["Five users is not proof of anything","I need to see thousands of users first","Sounds like vapourware"]'::jsonb, green_flag_signals = '["I like that it grew from real usage","Founding investors using it daily is a good sign","Show me the platform"]'::jsonb WHERE id = 'C3';

UPDATE belief_registry SET conversation_question = 'With VCT relief reducing in April 2026 and pension IHT changes in 2027, how do you see the timing for EIS?', content_if_unresolved = 'Send Doc 196 — regulatory timeline showing converging tailwinds for EIS demand.', red_flag_signals = '["Regulatory changes could go either way","I do not make decisions based on policy changes","This feels like artificial urgency"]'::jsonb, green_flag_signals = '["The regulatory tailwinds are real","VCT changes push people toward EIS","The pension IHT change is going to drive demand"]'::jsonb WHERE id = 'C4';

UPDATE belief_registry SET conversation_question = 'What do you think about a subscription-only model with no commissions or AUM fees?', content_if_unresolved = 'Send Doc 120 — business model breakdown: subscription only, no commission, no AUM, no trail.', red_flag_signals = '["Subscription models do not scale","How do you make enough revenue without AUM?","I do not trust free-from-conflict claims"]'::jsonb, green_flag_signals = '["No commission means no conflicts","Subscription aligns incentives with users","That is how it should be"]'::jsonb WHERE id = 'C5';

UPDATE belief_registry SET conversation_question = 'When you invest in an early-stage company, how important is a clear exit path?', content_if_unresolved = 'Send Doc 130 — identified acquirer categories: PitchBook/Morningstar, Bureau van Dijk, Refinitiv/LSEG.', red_flag_signals = '["There is no realistic acquirer for this","Data companies are not being acquired","The exit is too speculative"]'::jsonb, green_flag_signals = '["Those are credible acquirers","Data and analytics companies do get acquired","I can see the strategic fit"]'::jsonb WHERE id = 'C6';

UPDATE belief_registry SET conversation_question = 'Do you believe that independent EIS intelligence will become a must-have rather than a nice-to-have?', content_if_unresolved = 'Send Doc 120 — structural thesis: why independent EIS DD will become essential infrastructure.', red_flag_signals = '["IFAs will figure this out themselves","There is no structural need for this","Existing platforms will add EIS features"]'::jsonb, green_flag_signals = '["The advice gap is structural, not temporary","Nobody else is building this","Regulation is making this essential"]'::jsonb WHERE id = 'F0';

UPDATE belief_registry SET conversation_question = 'How do the founding round terms compare to other early-stage deals you have seen?', content_if_unresolved = 'Send Doc 120 — founding round term sheet and valuation rationale.', red_flag_signals = '["The valuation is too high","I have seen better terms elsewhere","I would want more equity for this stage"]'::jsonb, green_flag_signals = '["The terms are fair for this stage","EIS relief makes the entry price very attractive","I like the founder-friendly structure"]'::jsonb WHERE id = 'F1';

UPDATE belief_registry SET conversation_question = 'Do you see the EIS income tax relief as effectively HMRC co-investing alongside you?', content_if_unresolved = 'Send Doc 150 — reframes EIS relief as government co-investment, reducing effective entry cost.', red_flag_signals = '["That is just a tax break, not co-investment","I do not rely on tax incentives to make investment decisions"]'::jsonb, green_flag_signals = '["I had not thought of it that way","HMRC taking 30% of the risk changes the equation","Effectively paying 70p per pound is compelling"]'::jsonb WHERE id = 'F2';

UPDATE belief_registry SET conversation_question = 'Based on the acquirer landscape, does the exit path for Unlock feel clear to you?', content_if_unresolved = 'Send Doc 130 — maps Unlock capabilities to confirmed acquirer needs in data/analytics space.', red_flag_signals = '["I am not convinced anyone would buy this","The exit timeline is too uncertain","Too many things need to go right"]'::jsonb, green_flag_signals = '["The acquirer categories make sense","Data companies in this space are being acquired","I can see a 3-5 year exit path"]'::jsonb WHERE id = 'F3';
